# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a41fdc129056b04020dbe1a8087c47369f89858baf58cd85b70412b6032548bb8bc8da0f8d453fbe0bf0327ea6106339445fcaccabbf3f48d80afcabb4ba67d7

test:
  secret_key_base: 959a12aa61ec47d7df9899b05ea6ea52708f5b659bd1c8de4372b238c71309f73c300076afdfb75ec1b61e0596348e7e10fb0213ac971a02e70d5a204c3ff947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
